#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "age-online"
name = "age-online"
description.en = "Fully in-browser tool to encrypt data with age"
description.fr = "Fully in-browser tool to encrypt data with age"

version = "0.1.0~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "MIT"
code = "https://some.forge.com/example/example"

[integration]
yunohost = ">= 11.2.30"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/nkcmr/age-online/archive/802532a07bb93b018e15477bb19c83924405fe0b.tar.gz"
    sha256 = "b4ab66fba225f6ca079c0cd9941bc9fce78a920c3aae2b7733254cb2b3e35135"
    autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default = 3000

